title: Configuration
data:
  osmosis_simple_location: 'Takilma, OR'
  start_date: '2024-10-24'
  end_date: '2024-10-27'
  tickets_link: 'https://ra.co/events/1986191'
  error_404_entry: 059d4d8d-fc60-49f8-8823-7da10549e84e
  copyright_since: 2024
  privacy_statement_type: none
  cookie_notice_type: none
